---

checks:
  python:
    code_rating: true
    duplicate_code: true
build:
  nodes:
    analysis:
      tests:
        override:
          - command: pylint-run
            use_website_config: true
      environment:
        python: 3.6
filter:
  excluded_paths:
    - '*/tests/*'
